repos:
  - repo: local
    hooks:
    - id: deploy-docs
      name: deploy-docs
      description: This hook builds the docs and uploads them to gh.
      entry: make docs-deploy
      language: system
      pass_filenames: false
      stages: [push]
      
    - id: check
      name: check
      description: This hook checks the formatting of the code.
      entry: make check
      language: system
      pass_filenames: false
      stages: [commit]
